all::
	cd unlink_apache && make
	cd unlink_apache2 && make
	cd unlink_mysqld && make
	cd unlink_nginx && make
	cd unlink_proftpd && make

clean::
	cd unlink_apache && make clean
	cd unlink_apache2 && make clean
	cd unlink_mysqld && make clean
	cd unlink_nginx && make clean
	cd unlink_proftpd && make clean

