all::
	cd relinking && make
	cd unlink_apache && make
	cd unlink_apache2 && make
	cd unlink_mysqld && make
	cd unlink_nginx && make
	cd unlink_proftpd && make

clean::
	cd relinking && make clean
	cd unlink_apache && make clean
	cd unlink_apache2 && make clean
	cd unlink_mysqld && make clean
	cd unlink_nginx && make clean
	cd unlink_proftpd && make clean

test::
	cd relinking && make test
	cd unlink_apache && make test
	cd unlink_apache2 && make test
	cd unlink_mysqld && make test
	cd unlink_nginx && make test
	cd unlink_proftpd && make test

